user:
  outputs:
    default:
      account: QECOAIR-EY25178
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: EPIAS_DB
      password: Aycabayraktar2026*
      retry_on_database_errors: true
      role: null
      schema: DBT_DEV
      threads: 6
      type: snowflake
      user: AYCAIZE
      warehouse: COMPUTE_WH
  target: default
